[build]
  publish = "out/"
  command = "npm run build"

[[redirects]]
  from = "/article/did-i-just-discovered-a-new-mathematical-formula/*"
  to = "/article/did-i-just-discover-a-new-mathematical-formula/*"
  status = 301
  force = true